version: "3.3"
services:
  # dse:
  #   image: datastax/dse-server
  #   container_name: cassandra
  #   ports:
  #   - "9042:9042" # cassandra
  #   environment:
  #     DS_LICENSE: accept
  #   volumes:
  #   - "./cassandra/data:/var/lib/cassandra" # this is where files get saved
  #   # Allow DSE to lock memory with mlock
  #   cap_add:
  #   - IPC_LOCK
  #   ulimits:
  #     memlock: -1
  #   command: [ -s ]

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark-master:
    image: karelgoense/public:karelgoense-spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"

  spark-worker:
    image: karelgoense/public:karelgoense-spark
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    volumes:
      - "./data:/local"
    command: "/start-worker.sh"
    
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default