version: "3.7"
services:
  seed_node:
    container_name: cassandra
    image: "datastax/dse-server"
    environment:
      - DS_LICENSE=accept
    ports:
    - "9042:9042"
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    volumes:
      - "./cassandra/data:/var/lib/cassandra" # this is where files get saved
  node:
    image: "datastax/dse-server"
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
    links:
      - seed_node
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark-master:
    image: karelgoense/public:karelgoense-spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"

  spark-worker:
    image: karelgoense/public:karelgoense-spark
    depends_on:
      - spark-master
    ports:
      - 8080
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"

  client:
    image: karelgoense/public:karelgoense-spark
    container_name: client
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"
    # volumes:
    #   - "./apps:/local/apps"
    #   - "./conf:/spark/conf"