apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker
  name: spark-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker
    spec:
      containers:
      - args:
        - /start-worker.sh
        env:
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8080"
        image: karelgoense/public:karelgoense-spark
        name: spark-worker
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
